spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3307/cookingTutorialData"
    username: root
    password: admin123
  mail:
    host: smtp.gmail.com
    port: 587
    username: datcute279@gmail.com
    password: lyexpuxldyjdihhr
    properties:
      mail.smtp.auth: true
<<<<<<< HEAD
      mail.smtp.starttls: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
=======
      mail.smtp.starttls.enable: true
>>>>>>> 3f7efa78738a83d04f90a4a27eb960454be9a049
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "qV6MwxsMykj6Zou1ovsapONCduni7+NQ4I8YTOyITaaED/2CXu4V2XnJ7eiQInSS"
