spring:
  datasource:
    url: "mysql://mysql.railway.internal:39896:3306/railway"
    username: root
    password: yjbkkGaabflPmsUTbtADIhdpTnHxuUmP
  mail:
    host: smtp.gmail.com
    port: 587
    username: datcute279@gmail.com
    password: lyexpuxldyjdihhr
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "qV6MwxsMykj6Zou1ovsapONCduni7+NQ4I8YTOyITaaED/2CXu4V2XnJ7eiQInSS"
  cloudySecret: "066Vbfp6rEVB_lnxrtO_PFFRVmo"

